### PR TITLE
merge context branch into develop branch

### PR DESCRIPTION
**Pull request by spiderbiggen**
As a Developer I want to work with the latest environment version.

### CODE REVIEW

**Comment by tvleest** [comment]
This will enable us to use some of the new percepts till the merge with master is fixed.
approved.

**Comment by tvleest** [comment]
Don't forget to add a user story.

As a Developer I want to work with the latest environment version.

**Comment by MichielvdBerg** [comment]
With some new percepts, we can make more features in our agent. I approve.

**Comment by spiderbiggen** [comment]
@tvleest thanks forgot about that :(

**Pull request merged**
